# Introduction to Python
Run the hidden code cell below to import the data used in this course.

In [1]:
# Importing course packages; you can add more too!
import numpy as np
import math

# Import columns as numpy arrays
baseball_names = np.genfromtxt(
    fname="baseball.csv",  # This is the filename
    delimiter=",",  # The file is comma-separated
    usecols=0,  # Use the first column
    skip_header=1,  # Skip the first line
    dtype=str,  # This column contains strings
)
baseball_heights = np.genfromtxt(
    fname="baseball.csv", delimiter=",", usecols=3, skip_header=1
)
baseball_weights = np.genfromtxt(
    fname="baseball.csv", delimiter=",", usecols=4, skip_header=1
)
baseball_ages = np.genfromtxt(
    fname="baseball.csv", delimiter=",", usecols=5, skip_header=1
)

soccer_names = np.genfromtxt(
    fname="soccer.csv",
    delimiter=",",
    usecols=1,
    skip_header=1,
    dtype=str,
    encoding="utf", 
)
soccer_ratings = np.genfromtxt(
    fname="soccer.csv",
    delimiter=",",
    usecols=2,
    skip_header=1,
    encoding="utf", 
)
soccer_positions = np.genfromtxt(
    fname="soccer.csv",
    delimiter=",",
    usecols=3,
    skip_header=1,
    encoding="utf", 
    dtype=str,
)
soccer_heights = np.genfromtxt(
    fname="soccer.csv",
    delimiter=",",
    usecols=4,
    skip_header=1,
    encoding="utf", 
)
soccer_shooting = np.genfromtxt(
    fname="soccer.csv",
    delimiter=",",
    usecols=8,
    skip_header=1,
    encoding="utf", 
)

   ### Python Basics

- General Purpose: Build Anything
- Open Source ! Free !
- Python Packages , also for data scienceyour notes here_

#### Comment

- Use for understanding code
- Use '#' to comment

In [2]:
# Print my name

name = 'Sawrab'

print(name)

Sawrab


In [3]:
# Calculation in python

# Addition
print(4+5)

# Subtraction
print(5-5)

# Multiplication
print(3*5)

# Division
print(10/2)

# Modulas
print(10%4)

# Floor division
print(6//2)

9
0
15
5.0
2
3


#### Variable

In Python, a variable allows you to refer to a value with a name

In [4]:
age = 23 # Here age is called variable name and 23 is value. Value assin using '='(assingment) operator

print(age)

23


In [5]:
# Another Example

year = 2024

print(year)

2024


In [6]:
# Calculation using variable

monthly_savings = 30
months = 12

Yearly_saving = monthly_savings * months

print(Yearly_saving)

360


#### Data Type

- String
- Float
- Int
- Boolean

In [7]:
name = 'Sawrab'

print(type(name))

<class 'str'>


In [8]:
water = 2.5

print(type(water))

<class 'float'>


In [9]:
Taste_good = True 

print(type(Taste_good))

<class 'bool'>


#### Operations With Types

Different types different behavior

In [10]:
a = 5
b = 6

sum = a+b
print(sum)

11


In [11]:
First_name = 'Md'
last_name = 'Sawrab'

Full_name = First_name + ' ' + last_name 
print(Full_name)

Md Sawrab


#### Type Conversion

In [12]:
# Int to Str

age = 21 # Here value in int type

new_type = str(age)
print(type(new_type))

<class 'str'>


### Python List

#### Creating list

- List containt any types
- List start and end with '[]'

In [13]:
name_list = ['ashik', 'imran', 'sawrab','jahidul']

print(name_list)

['ashik', 'imran', 'sawrab', 'jahidul']


In [14]:
print(type(name_list))

<class 'list'>


In [15]:
# list with different types

diff_types_list = ['ashik', 'imran', 21,22,5.7]

print(diff_types_list)

['ashik', 'imran', 21, 22, 5.7]


In [16]:
# list of list

name_age = [['ashik', 24], ['imran', 22]]

print(name_age)

[['ashik', 24], ['imran', 22]]


#### Subsetting and slicing

Indexing start with 0

In [17]:
name_list = ['ashik', 'imran', 'sawrab','jahidul']

# access jahidul from name_list

print(name_list[3])

jahidul


In [18]:
print(name_list[-1]) # is called negative indexing

jahidul


In [19]:
# Subsetting and Calculation

tk = [30,4,56,7,8]

A30_ = tk[0]
B56_ = tk[2]

total = A30_ + B56_

print(total)

86


In [20]:
# Slicing 

name_list = ['ashik', 'imran', 'sawrab','jahidul']

print(name_list[0:3]) # last number excluted form output


['ashik', 'imran', 'sawrab']


In [21]:
print(name_list[:4])

print(name_list[1:])

['ashik', 'imran', 'sawrab', 'jahidul']
['imran', 'sawrab', 'jahidul']


In [22]:
# Subsetting list of list

name_age = [['ashik', 24], ['imran', 22]]

print(name_age[0][1])

24


#### Manipulate list

In [23]:
# Replace
name_list = ['ashik', 'imran', 'sawrab','jahidul']

name_list[3] = 'rakib'

print(name_list)

['ashik', 'imran', 'sawrab', 'rakib']


In [24]:
# Extend

list_ext = name_list + ['Jahidul']

print(list_ext)

['ashik', 'imran', 'sawrab', 'rakib', 'Jahidul']


In [25]:
# Remove

del list_ext[2]

list_ext

['ashik', 'imran', 'rakib', 'Jahidul']

### Function and Package

Python offers a bunch of built-in functions to make your life as a data scientist easier. You already know two such functions: print() and type(). You've also used the functions str(), int(), bool() and float() to switch between data types. These are built-in functions as well.

#### Basic Function

In [26]:
name = 'sawrab'

type(name) # this is a build in function

str

In [27]:
len(name) # this is also

6

In [28]:
list_ = [1,2,3,4,5,6,7,8,9]

sort = sorted(list_, reverse = True) # reverse = True returned desending order

sort

[9, 8, 7, 6, 5, 4, 3, 2, 1]

#### String Method

In [29]:
print(name.upper())

SAWRAB


#### List Method

- index(), to get the index of the first element of a list that matches its input and
- count(), to get the number of times an element appears in a list.

In [30]:
name_list = ['ashik', 'imran', 'sawrab','jahidul']

print(name_list.index('sawrab'))

2


In [31]:
print(name_list.count('sawrab'))

1


In [32]:
name_list.append('rabbi')
name_list

['ashik', 'imran', 'sawrab', 'jahidul', 'rabbi']

In [33]:
name_list.reverse()

name_list

['rabbi', 'jahidul', 'sawrab', 'imran', 'ashik']

#### Import Package

In [34]:
import math

# Definition of radius
r = 0.43

C = 2*(math.pi)*3

A = math.pi*3**2

print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 18.84955592153876
Area: 28.274333882308138


In [35]:
# Selective import
from math import radians

# Definition of radius
r = 192500

# Travel distance of Moon over 12 degrees. Store in dist.
dist = r*radians(12)

# Print out dist
print(dist)

40317.10572106901


### Numpy

#### Create Numpy array

In [36]:
# Import numpy 

import numpy as np 

In [37]:
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

np_baseball = np.array(baseball)

print(np_baseball)

[180 215 210 210 188 176 209 200]


#### Subsetting

In [38]:
np_baseball[2]

210

In [39]:
np_baseball[2:5]

array([210, 210, 188])

#### 2D array

In [40]:
age = [[2000, 24], [2002, 22]]

np_age = np.array(age)

np.ndim(np_age)

2

In [41]:
# Subsetting 2D array

np_age[0,0:2]

array([2000,   24])

#### Numpy Statistics

In [42]:
stat = [1,2,3,4,5,6,7,8,9,3,4,5]

np_stat = np.array(stat)

In [43]:
# mean

np_stat.mean()

4.75

In [44]:
# median

np.median(np_stat)

4.5